<a href="https://colab.research.google.com/github/Muzhi1920/awesome-models/blob/main/01-basic_layer_op/00_batch_norm_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## batch norm
1. layer是横向处理，对该样本内的units输出，进行规范化；
2. batch是纵向处理，获得该mini-batch的均值方差，得到样本间的规范化输出

假设mini-batch一共有N个样本，则Batch Normalization是对纵向按照维度进行归一，而Layer Normalization对于单个的样本内进行规范化处理

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Layer, Dense, LayerNormalization, Dropout, Embedding
import numpy as np

In [ ]:
data = tf.constant(np.arange(10).reshape(5, 2), dtype=tf.float32)
data

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]], dtype=float32)>

In [ ]:
layer = tf.keras.layers.BatchNormalization()
layer

In [ ]:
layer(data)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0.       , 0.9995004],
       [1.9990008, 2.9985013],
       [3.9980016, 4.997502 ],
       [5.9970026, 6.996503 ],
       [7.996003 , 8.995503 ]], dtype=float32)>

- `gamma * (batch - mean(batch)) / sqrt(var(batch) + epsilon) + beta`
- `gamma * (batch - self.moving_mean) / sqrt(self.moving_var + epsilon) + beta`.
- `moving_mean = moving_mean * momentum + mean(batch) * (1 - momentum)`
- `moving_var = moving_var * momentum + var(batch) * (1 - momentum)`

1. 初始化：self.mean=0,self.var=1,
2. 用于迭代：momentum=0.99

batch_norm_layer：设定moving_mean,moving_var，来调整不同batch的均值方差

In [ ]:
(data)/np.sqrt(1+0.001)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0.       , 0.9995004],
       [1.9990008, 2.9985013],
       [3.9980016, 4.997502 ],
       [5.9970026, 6.996503 ],
       [7.996003 , 8.995503 ]], dtype=float32)>

基本认同https://zhuanlan.zhihu.com/p/38755603
1. layer_norm，横向对该样本内的输出进行规范化；
2. batch_norm，纵向对该mini-batch的样本进行规范化