## layer norm layer
独立地对该batch中每个样本的前一层的激活输出进行标准化，来维持每个激活输出的均值接近0，标准差接近1。

---

batch norm是跨批次的进行`Normlization`。
1. layer norm是对样本内的输出进行规范化，`axis`一般是横向；
2. batch norm是对样本外的输出，`axis`一般是跨样本的纵向；

给定张量“输入”，计算矩并归一化，在 `axis` 中指定的轴上执行。


In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Layer, Dense, LayerNormalization, Dropout, Embedding
import numpy as np

In [ ]:
data = tf.constant(np.arange(30).reshape(5, 6) * 10, dtype=tf.float32)
data

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[  0.,  10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100., 110.],
       [120., 130., 140., 150., 160., 170.],
       [180., 190., 200., 210., 220., 230.],
       [240., 250., 260., 270., 280., 290.]], dtype=float32)>

In [ ]:
layer = tf.keras.layers.LayerNormalization(axis=1)
layer

In [ ]:
output = layer(data)
output

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[-1.4638475 , -0.87830853, -0.2927695 ,  0.2927695 ,  0.87830853,
         1.4638475 ],
       [-1.4638475 , -0.87830853, -0.2927695 ,  0.2927695 ,  0.87830853,
         1.4638475 ],
       [-1.4638475 , -0.87830853, -0.2927695 ,  0.2927695 ,  0.87830853,
         1.4638475 ],
       [-1.4638475 , -0.87830853, -0.2927695 ,  0.2927695 ,  0.87830853,
         1.4638475 ],
       [-1.4638475 , -0.87830853, -0.2927695 ,  0.2927695 ,  0.87830853,
         1.4638475 ]], dtype=float32)>

## 结论
1. 对每一样本的输出，按照给定`axis`进行normalization
2. 而不是不同的样本间

## 引入gamma和beta
1. 在原先0，1标准正态分布基础上进行缩放和平移；
2. 初始化为0，和1，可训练。

`output_i = x_i_normalized * gamma + beta`

In [ ]:
layer = tf.keras.layers.LayerNormalization(axis=[1, 2, 3])
layer

In [ ]:
layer.build([5, 20, 30, 40])
layer

In [ ]:
layer.beta.shape,layer.gamma.shape

(TensorShape([20, 30, 40]), TensorShape([20, 30, 40]))