<a href="https://colab.research.google.com/github/Muzhi1920/awesome-models/blob/main/04-feature_column/04_SequenceCategoricalColumn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.python.ops import array_ops,math_ops,sparse_ops


In [ ]:
##解析该函数，这里将sequence_category_column适配于embedding_lookup，沿最后一维进行segment_pooling；实现输出为序列emb
def _get_sparse_tensors_helper(self, sparse_tensors):
    id_tensor = sparse_tensors.id_tensor
    weight_tensor = sparse_tensors.weight_tensor
    # Expands third dimension, if necessary so that embeddings are not
    # combined during embedding lookup. If the tensor is already 3D, leave
    # as-is.
    shape = array_ops.shape(id_tensor)
    # Compute the third dimension explicitly instead of setting it to -1, as
    # that doesn't work for dynamically shaped tensors with 0-length at runtime.
    # This happens for empty sequences.
    target_shape = [shape[0], shape[1], math_ops.reduce_prod(shape[2:])]
    id_tensor = sparse_ops.sparse_reshape(id_tensor, target_shape)
    if weight_tensor is not None:
      weight_tensor = sparse_ops.sparse_reshape(weight_tensor, target_shape)

In [ ]:
id_tensor = tf.sparse.SparseTensor(indices=[[0,0],[0,1],[0,2],[1,0],[1,1],[2,0],[2,1],[3,0]],
                                    values=[123,234,11,1245,124,2121,124,2121],
                                    dense_shape=[4,3])
id_tensor,tf.sparse.to_dense(id_tensor)

(<tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7fe2e13cecd0>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ 123,  234,   11],
        [1245,  124,    0],
        [2121,  124,    0],
        [2121,    0,    0]], dtype=int32)>)

In [ ]:
shape = array_ops.shape(id_tensor)
shape,shape[2:]

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 3], dtype=int32)>,
 <tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>)

In [ ]:
target_shape = [shape[0], shape[1], math_ops.reduce_prod(shape[2:])]
target_shape

[<tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>]

In [ ]:
id_tensor =sparse_ops.sparse_reshape(id_tensor, target_shape)
id_tensor,tf.sparse.to_dense(id_tensor)

(<tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7fe2e1383a90>,
 <tf.Tensor: shape=(4, 3, 1), dtype=int32, numpy=
 array([[[ 123],
         [ 234],
         [  11]],
 
        [[1245],
         [ 124],
         [   0]],
 
        [[2121],
         [ 124],
         [   0]],
 
        [[2121],
         [   0],
         [   0]]], dtype=int32)>)

In [ ]:

    # Expands third dimension, if necessary so that embeddings are not
    # combined during embedding lookup. If the tensor is already 3D, leave
    # as-is.
    # Compute the third dimension explicitly instead of setting it to -1, as
    # that doesn't work for dynamically shaped tensors with 0-length at runtime.
    # This happens for empty sequences.
    
    # if weight_tensor is not None:
    #   weight_tensor = sparse_ops.sparse_reshape(weight_tensor, target_shape)