<a href="https://colab.research.google.com/github/Muzhi1920/awesome-models/blob/main/04-feature_column/04_SequenceFeaturesColumn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow import feature_column as fc
import tensorflow as tf
from sequence_feature_layer import SequenceFeatures

In [ ]:
kw = fc.sequence_categorical_column_with_hash_bucket('aaa', hash_bucket_size=10, dtype=tf.int64)
dank = fc.sequence_categorical_column_with_hash_bucket('bbb', hash_bucket_size=10, dtype=tf.int64)
kw_col = fc.embedding_column(kw, dimension=4)
dank_col = fc.embedding_column(dank, dimension=6)
columns = [kw_col,dank_col]

In [ ]:
kw

SequenceCategoricalColumn(categorical_column=HashedCategoricalColumn(key='aaa', hash_bucket_size=10, dtype=tf.int64))

In [ ]:
features={
  "aaa": tf.sparse.SparseTensor(
      indices=[[0, 0], [0, 1], [1, 0]],
      values=[1100, 1101, 1102],
      dense_shape=[2, 2]),
  "bbb": tf.sparse.SparseTensor(
      indices=[[1, 0]],
      values=[100],
      dense_shape=[2, 1]),
}

In [ ]:
tf.sparse.to_dense(features['aaa'])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1100, 1101],
       [1102,    0]], dtype=int32)>

In [ ]:
sequence_feature_layer = SequenceFeatures(columns)

In [ ]:
sequence_input, sequence_length = sequence_feature_layer(features)

target_shape tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(2, shape=(), dtype=int32) 4
target_shape tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(1, shape=(), dtype=int32) 6


In [ ]:
sequence_input

{'aaa_embedding': <tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
 array([[[-0.20366316, -0.25406513,  0.31047094,  0.69951296],
         [-0.05266371,  0.2547182 , -0.0093221 ,  0.9389799 ]],
 
        [[ 0.04222297, -0.6708118 ,  0.17080276, -0.9551269 ],
         [ 0.        ,  0.        ,  0.        ,  0.        ]]],
       dtype=float32)>,
 'bbb_embedding': <tf.Tensor: shape=(2, 1, 6), dtype=float32, numpy=
 array([[[ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ]],
 
        [[ 0.67249227, -0.14938436,  0.39018124, -0.14576633,
          -0.2823811 , -0.02786766]]], dtype=float32)>}

In [ ]:
sequence_length

{'aaa_embedding': <tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 1])>,
 'bbb_embedding': <tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 1])>}