<a href="https://colab.research.google.com/github/Muzhi1920/awesome-models/blob/main/02-basic_tensor_op/01_arrays_op.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.python.framework import ops
from tensorflow.python.ops import array_ops,math_ops,nn_ops,gen_array_ops

gen_array_ops在矩阵变换中，使用到了生成op

# 矩阵维度
## 维度变换

In [ ]:
input_tensor = tf.constant([[1,2,3,4],[4,3,2,1],[0,0,1,0],[1,1,1,0]])
input_tensor

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [0, 0, 1, 0],
       [1, 1, 1, 0]], dtype=int32)>

### reshape
1. 返回同序，同值的Tensor；除非新shape
2. -1，按照其他维度计算后得到对应维度；
3. [-1]意味着拍平为一维；最多一个-1

In [ ]:
tf.reshape(input_tensor,[2,8])

<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[1, 2, 3, 4, 4, 3, 2, 1],
       [0, 0, 1, 0, 1, 1, 1, 0]], dtype=int32)>

### expand_dims
扩展维度
1. input
2. axis 哪个维度上扩展
3. dim deprecated

In [ ]:
image = tf.zeros([2,3,2])
tf.expand_dims(image, axis=0),tf.expand_dims(image, axis=1),tf.expand_dims(image, -1)

(<tf.Tensor: shape=(1, 2, 3, 2), dtype=float32, numpy=
 array([[[[0., 0.],
          [0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.],
          [0., 0.]]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 1, 3, 2), dtype=float32, numpy=
 array([[[[0., 0.],
          [0., 0.],
          [0., 0.]]],
 
 
        [[[0., 0.],
          [0., 0.],
          [0., 0.]]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 2, 1), dtype=float32, numpy=
 array([[[[0.],
          [0.]],
 
         [[0.],
          [0.]],
 
         [[0.],
          [0.]]],
 
 
        [[[0.],
          [0.]],
 
         [[0.],
          [0.]],
 
         [[0.],
          [0.]]]], dtype=float32)>)

### squeeze
1. 删除size为1的维度；
2. 删除指定位置的维度，要求size也为1.

In [ ]:
t = tf.ones([1, 2, 1, 3, 1, 1])
t,array_ops.squeeze(t)

(<tf.Tensor: shape=(1, 2, 1, 3, 1, 1), dtype=float32, numpy=
 array([[[[[[1.]],
 
           [[1.]],
 
           [[1.]]]],
 
 
 
         [[[[1.]],
 
           [[1.]],
 
           [[1.]]]]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

In [ ]:
tf.squeeze(t, [2, 4])

<tf.Tensor: shape=(1, 2, 3, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]]], dtype=float32)>

## 维度

### shape/size/rank
1. 返回Tensor的shape;
2. size(num_elements)
3. 返回秩；Tensor和矩阵的秩不同；Tensor的秩是指获取到元素时，所需要的索引数

In [ ]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]], [[3, 3, 3], [4, 4, 4]]])
tf.shape(t), tf.shape_n(t),tf.size(t),tf.rank(t)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 3], dtype=int32)>,
 [<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>,
  <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>,
  <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>],
 <tf.Tensor: shape=(), dtype=int32, numpy=18>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

### broadcast_dynamic_shape
结合不同长度的特征向量

In [ ]:
shape_x = tf.TensorShape([1, 2, 1])
shape_y = tf.TensorShape([5, 1 ,3])
tf.broadcast_static_shape(shape_x, shape_y),tf.broadcast_dynamic_shape(shape_x, shape_y)

(TensorShape([5, 2, 3]),
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 2, 3], dtype=int32)>)

### \_check_index
"""Check if a given value is a valid index into a tensor；check给定值是否是一个tensor的合法索引"""

In [ ]:
array_ops._check_index(1)

### \_all_dimensions

In [ ]:
array_ops._all_dimensions(t)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

# 矩阵生成

## 构造

### zeros/ones
1. shape

In [ ]:
tf.zeros([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

### zeros_like/ones_like
1. input，输入的tensor；
2. 返回和input，相同的zeros

In [ ]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.zeros_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

### one-hot
1. depth：代表one-hot的维度

In [ ]:
tf.one_hot([0,4,3,],6)

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.]], dtype=float32)>

### sequence_mask
1.隐码个数、维度；
2. 按照输入维度，构造隐码；取最大长度

In [ ]:
tf.sequence_mask([1, 3, 2], 5)

<tf.Tensor: shape=(3, 5), dtype=bool, numpy=
array([[ True, False, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True, False, False, False]])>

In [ ]:
tf.sequence_mask([[1, 3],[2,0]])

<tf.Tensor: shape=(2, 2, 3), dtype=bool, numpy=
array([[[ True, False, False],
        [ True,  True,  True]],

       [[ True,  True, False],
        [False, False, False]]])>

### matrix_diag
1. diagonal：对角矩阵的元素；
2. k=0；num_rows=-1；num_cols=-1；padding_value=0；align="RIGHT_LEFT"

In [ ]:
diagonal = [[1, 2, 3, 4],[5, 6, 7, 8]]
array_ops.matrix_diag(diagonal)

<tf.Tensor: shape=(2, 4, 4), dtype=int32, numpy=
array([[[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]],

       [[5, 0, 0, 0],
        [0, 6, 0, 0],
        [0, 0, 7, 0],
        [0, 0, 0, 8]]], dtype=int32)>

In [ ]:
# A superdiagonal (per batch).
diagonal = [[1, 2, 3],[4, 5, 6]]
array_ops.matrix_diag(diagonal, k = 1)

<tf.Tensor: shape=(2, 4, 4), dtype=int32, numpy=
array([[[0, 1, 0, 0],
        [0, 0, 2, 0],
        [0, 0, 0, 3],
        [0, 0, 0, 0]],

       [[0, 4, 0, 0],
        [0, 0, 5, 0],
        [0, 0, 0, 6],
        [0, 0, 0, 0]]], dtype=int32)>

In [ ]:
# A tridiagonal band (per batch).
diagonals = [[[8, 9, 0],[1, 2, 3],[0, 4, 5]],
                      [[2, 3, 0],[6, 7, 9],[0, 9, 1]]]
array_ops.matrix_diag(diagonals, k = (-1, 1)),"看不懂，后面其他也看不懂"

(<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[1, 9, 0],
         [0, 2, 0],
         [0, 4, 3]],
 
        [[6, 3, 0],
         [0, 7, 0],
         [0, 9, 9]]], dtype=int32)>,
 '看不懂，后面其他也看不懂')

### fill
填充值

In [ ]:
tf.fill([2, 3], 1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

### gather/batch_gather
1. 按照indices，收集params；拼接成新的tensor

In [ ]:
a = [1, 2, 3, 4, 5, 0, 0, 0,1, 2, 0, 0, 0, 0, 0, 0,1, 2, 3, 4, 0, 0, 0, 0,1, 2, 3, 4, 5, 6, 7, 8]
b = [0,1,2,3,7,4,10]
array_ops.gather(a,b),array_ops.batch_gather(a,b)

Instructions for updating:
`tf.batch_gather` is deprecated, please use `tf.gather` with `batch_dims=-1` instead.


(<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 3, 4, 0, 5, 0], dtype=int32)>,
 <tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 3, 4, 0, 5, 0], dtype=int32)>)

### tensor_scatter_nd_update
1. 按照索引，替换tensor的值

In [ ]:
indices= array_ops.reshape(b,[-1,1])
updates = [9, 99, 999, 9999, 99999, 999999, 9999999]
indices,array_ops.tensor_scatter_nd_update(a, indices, updates)

(<tf.Tensor: shape=(7, 1), dtype=int32, numpy=
 array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 7],
        [ 4],
        [10]], dtype=int32)>,
 <tf.Tensor: shape=(32,), dtype=int32, numpy=
 array([      9,      99,     999,    9999,  999999,       0,       0,
          99999,       1,       2, 9999999,       0,       0,       0,
              0,       0,       1,       2,       3,       4,       0,
              0,       0,       0,       1,       2,       3,       4,
              5,       6,       7,       8], dtype=int32)>)

### identity
它是通过在计算图内部创建 send / recv节点来引用或复制变量的，最主要的用途就是更好的控制在不同设备间传递变量的值.

In [ ]:
a = tf.Variable(5)
print(a)
a_identity = tf.identity(a)
a_identity,a.assign_add(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>


(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=6>)

## 矩阵比较

### setdiff1d
取两个Tensor的差集

In [ ]:
x = [1, 2, 3, 4, 5, 6]
y = [1, 3, 5]
array_ops.setdiff1d(x,y)

Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.sets.difference().


ListDiff(out=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>, idx=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 5], dtype=int32)>)

### boolean_mask
按照boolean的mask数组，取对应维度的tensor

In [ ]:
# 1-D example
tensor = [0, 1, 2, 3]
mask = [True, False, True, False]
tf.boolean_mask(tensor, mask)  # [0, 2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2], dtype=int32)>

In [ ]:
# 2-D example
tensor = [[1, 2], [3, 4], [5, 6]]
mask = [True, False, True]
tf.boolean_mask(tensor, mask)  # [[1, 2], [5, 6]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6]], dtype=int32)>

### sparse_mask

In [ ]:
cur_sparse = tf.sparse.SparseTensor(indices=[[0,0],[0,1],[1,0],[2,0],[2,2],[3,0],[4,1]],
                                    values=[1213,1212,20,1,12,34,32],
                                    dense_shape=[5,3])
cur_sparse,tf.sparse.to_dense(cur_sparse)
# res = tf.sparse.mask(cur_sparse, [0,1])
# res.indices,res.values  # [2, 10]
"未发现用处"

'未发现用处'

### unique/with_counts
1. 得到某tensor的集合；
2. 返回集合，及其对应的下标；可按照下标恢复原tensor；
3. 返回每个元素的频次

In [ ]:
x = tf.constant([1, 1, 2, 4, 4, 4, 7, 8, 8])
y,z = tf.unique(x)
y,z

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 4, 7, 8], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 0, 1, 2, 2, 2, 3, 4, 4], dtype=int32)>)

In [ ]:
x = tf.constant([1, 1, 2, 4, 4, 4, 7, 8, 8])
y, idx, count = tf.unique_with_counts(x)
y,idx,count

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 4, 7, 8], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 0, 1, 2, 2, 2, 3, 4, 4], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 1, 3, 1, 2], dtype=int32)>)

# 矩阵变换
## 切片

### slice
从Tensor中抽取分片;
1. `size[i] = input_.dim_size(i) - begin[i]`
2. 从`begin`开始, tensor shape表示的size；`size[i]` 表示从第'i'维上所取的元素数
3. begin从0开始，size从1开始

In [ ]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                   [[3, 3, 3], [4, 4, 4]],
                   [[5, 5, 5], [6, 6, 6]]])
t,tf.slice(t, [1, 0, 0], [1, 1, 3])

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[1, 1, 1],
         [2, 2, 2]],
 
        [[3, 3, 3],
         [4, 4, 4]],
 
        [[5, 5, 5],
         [6, 6, 6]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[3, 3, 3]]], dtype=int32)>)

In [ ]:
tf.slice(t, [1, 0, 0], [1, 2, 2])

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[3, 3],
        [4, 4]]], dtype=int32)>

### strided_sice
1. input,begin,end,strides
2. 分片大小为size = `(end-begin)/stride`；
3. 以当前位置开始，取size大小的矩阵。

In [ ]:
tf.strided_slice(t, [1, 0, 0], [2, 1, 3], [1, 1, 1])
# 第一维是开区间

<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[3, 3, 3]]], dtype=int32)>

In [ ]:
tf.strided_slice(t, [1, 0, 0], [2, 2, 3], [1, 1, 1])

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[3, 3, 3],
        [4, 4, 4]]], dtype=int32)>

In [ ]:
tf.strided_slice(t, [1, -1, 0], [2, -3, 3], [1, -1, 1])
# 负号，代表[[3],[4]]，倒数

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[4, 4, 4],
        [3, 3, 3]]], dtype=int32)>

### split

In [ ]:
# 对第二维，按照4，4的大小，分成两份
x=[[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]
array_ops.split(x, [4, 4], axis=1)

[<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 2, 3, 4],
        [1, 2, 3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[5, 6, 7, 8],
        [5, 6, 7, 8]], dtype=int32)>]

## 组合

### parallel_stack/stack
1. parallel不支持bp；stack支持；
2. 堆放一个rank-`R`的tensors 为rank-`(R+1)` tensor；
3. Given a list of length `N` of tensors of shape `(A, B, C)`;
4. if `axis == 0` then the `output` tensor will have the shape `(N, A, B, C)`.
5. if `axis == 1` then the `output` tensor will have the shape `(A, N, B, C)`.
6. 增加维度的拼接，和concat不同

In [ ]:
x = tf.constant([[1,4],[1,4]])
y = tf.constant([[2,5],[2,5]])
z = tf.constant([[3,6],[3,6]])
x,tf.stack([x, y, z],axis=0),tf.stack([x, y, z],axis=1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 4],
        [1, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
 array([[[1, 4],
         [1, 4]],
 
        [[2, 5],
         [2, 5]],
 
        [[3, 6],
         [3, 6]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
 array([[[1, 4],
         [2, 5],
         [3, 6]],
 
        [[1, 4],
         [2, 5],
         [3, 6]]], dtype=int32)>)

### unstack
1. Unpacks rank-`R` tensor为rank-`(R-1)` tensors；
2. given a tensor of shape `(A, B, C, D)`；
3. If `axis == 0` then the i'th tensor in `output` is the slice`value[i, :, :, :]` and each tensor in `output` will have shape `(B, C, D)`.
4. If `axis == 1` then the i'th tensor in `output` is the slice`value[:, i, :, :]` and each tensor in `output` will have shape `(A, C, D)`.
5. 返回解包后的list

In [ ]:
x = tf.constant([[1,4],[1,4]])
y = tf.constant([[2,5],[2,5]])
z = tf.constant([[3,6],[3,6]])
a = tf.stack([x, y, z],axis=0)
a

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 4],
        [1, 4]],

       [[2, 5],
        [2, 5]],

       [[3, 6],
        [3, 6]]], dtype=int32)>

In [ ]:
b=tf.unstack(a,axis=0)
b

[<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 4],
        [1, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 5],
        [2, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[3, 6],
        [3, 6]], dtype=int32)>]

### concat
1. axis，按照某维度拼接；

In [ ]:
tf.concat(b,axis=1),tf.concat(b,axis=0)

(<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[1, 4, 2, 5, 3, 6],
        [1, 4, 2, 5, 3, 6]], dtype=int32)>,
 <tf.Tensor: shape=(6, 2), dtype=int32, numpy=
 array([[1, 4],
        [1, 4],
        [2, 5],
        [2, 5],
        [3, 6],
        [3, 6]], dtype=int32)>)

In [ ]:
x = tf.constant(tf.random.uniform([3, 8], -1, 1))
s0, s1, s2 = tf.split(x, num_or_size_splits=3, axis=0)
s0,s1,s2

(<tf.Tensor: shape=(1, 8), dtype=float32, numpy=
 array([[ 5.7410979e-01, -7.6293945e-04, -4.7076225e-02, -8.6661029e-01,
         -6.0015273e-01, -4.5935416e-01, -9.3237591e-01,  6.4132524e-01]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 8), dtype=float32, numpy=
 array([[-0.02825642,  0.16726208, -0.68280125,  0.38965058,  0.85696006,
          0.28510857,  0.8728919 , -0.494231  ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 8), dtype=float32, numpy=
 array([[-0.32020926, -0.35197496,  0.9064059 , -0.6801567 ,  0.8475621 ,
          0.36474967,  0.45799208, -0.6246288 ]], dtype=float32)>)

### repeat
1. 输入input
2. 重复input的元素
3. 沿着某axis进行repeat，空时，reshape成1-D再进行repeat

In [ ]:
array_ops.repeat(['a', 'b', 'c'], repeats=[3, 0, 2], axis=0)

<tf.Tensor: shape=(5,), dtype=string, numpy=array([b'a', b'a', b'a', b'c', b'c'], dtype=object)>

In [ ]:
array_ops.repeat([[1, 2], [3, 4]], repeats=[2, 3], axis=0)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]], dtype=int32)>

In [ ]:
array_ops.repeat([[1, 2], [3, 4]], repeats=[2, 3], axis=1)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 1, 2, 2, 2],
       [3, 3, 4, 4, 4]], dtype=int32)>

In [ ]:
array_ops.repeat(3, repeats=4)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 3, 3, 3], dtype=int32)>

In [ ]:
array_ops.repeat([[1,2], [3,4]], repeats=2)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)>

### transpose
1. 转置
2. `perm`it is set to (n-1...0)，输入维度的排列

In [ ]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.transpose(x),tf.transpose(x, perm=[1, 0])

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [3, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [3, 6]], dtype=int32)>)

In [ ]:
# 复数，设置conjugate=True，转置且共轭
x = tf.constant([[1 + 1j, 2 + 2j, 3 + 3j],
                 [4 + 4j, 5 + 5j, 6 + 6j]])
tf.transpose(x, conjugate=True)

<tf.Tensor: shape=(3, 2), dtype=complex128, numpy=
array([[1.-1.j, 4.-4.j],
       [2.-2.j, 5.-5.j],
       [3.-3.j, 6.-6.j]])>

In [ ]:
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])
# Take the transpose of the matrices in dimension-0
# (this common operation has a shorthand `linalg.matrix_transpose`)
tf.transpose(x, perm=[0, 2, 1]),"没看懂"

(<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
 array([[[ 1,  4],
         [ 2,  5],
         [ 3,  6]],
 
        [[ 7, 10],
         [ 8, 11],
         [ 9, 12]]], dtype=int32)>,
 '没看懂')

### 

In [ ]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.linalg.matrix_transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
x = tf.constant([[1 + 1j, 2 + 2j, 3 + 3j],
                 [4 + 4j, 5 + 5j, 6 + 6j]])
tf.linalg.matrix_transpose(x, conjugate=True)

<tf.Tensor: shape=(3, 2), dtype=complex128, numpy=
array([[1.-1.j, 4.-4.j],
       [2.-2.j, 5.-5.j],
       [3.-3.j, 6.-6.j]])>

#### 矩阵相乘
1. %%time 当前cell执行完所耗时间；
2. %time 当前行执行所耗时间
3. %timeit 对当前行之行1000次消耗时间的统计

In [ ]:
%%time
# Good!  Transpose is taken at minimal additional cost.
tf.matmul(x, x, transpose_b=True)

CPU times: user 2.38 ms, sys: 965 µs, total: 3.35 ms
Wall time: 2.08 ms


<tf.Tensor: shape=(2, 2), dtype=complex128, numpy=
array([[0. +28.j, 0. +64.j],
       [0. +64.j, 0.+154.j]])>

In [ ]:
%%time
# Inefficient!
tf.matmul(x, tf.linalg.matrix_transpose(x)),"果然！"

CPU times: user 432 µs, sys: 940 µs, total: 1.37 ms
Wall time: 810 µs


(<tf.Tensor: shape=(2, 2), dtype=complex128, numpy=
 array([[0. +28.j, 0. +64.j],
        [0. +64.j, 0.+154.j]])>,
 '果然！')

### pad
1. `paddings`维度 `[n, 2]`，n是tensor的维度. For each dimension D of `input`, `paddings[D, 0]` indicates how
many values to add before the contents of `tensor` in that dimension, and `paddings[D, 1]` indicates how many values to add after the contents of `tensor` in that dimension. 
2. 意思就是padding=[[1,2],[3,4]]，对应上下左右多少个0
3. If `mode` is "REFLECT" then both `paddings[D, 0]` and `paddings[D, 1]` must be no greater than `tensor.dim_size(D) - 1`. If `mode` is "SYMMETRIC" then both `paddings[D, 0]` and `paddings[D, 1]` must be no greater than `tensor.dim_size(D)`.

In [ ]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1,2], [3, 4]])
tf.pad(t, paddings, "CONSTANT")

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 5, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
paddings = tf.constant([[1,1], [2,2]])
tf.pad(t, paddings, "REFLECT"),tf.pad(t, paddings, "SYMMETRIC"),"没看懂"

(<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
 array([[6, 5, 4, 5, 6, 5, 4],
        [3, 2, 1, 2, 3, 2, 1],
        [6, 5, 4, 5, 6, 5, 4],
        [3, 2, 1, 2, 3, 2, 1]], dtype=int32)>,
 <tf.Tensor: shape=(4, 7), dtype=int32, numpy=
 array([[2, 1, 1, 2, 3, 3, 2],
        [2, 1, 1, 2, 3, 3, 2],
        [5, 4, 4, 5, 6, 6, 5],
        [5, 4, 4, 5, 6, 6, 5]], dtype=int32)>,
 '没看懂')

# 其他

### edit_distance
1. 计算编辑距离：Levenshtein distance between sequences


In [ ]:
hypothesis = tf.SparseTensor([[0, 0, 0],
                              [1, 0, 0]],
                             ["a", "b"],(2, 1, 1))
truth = tf.SparseTensor([[0, 1, 0],
                         [1, 0, 0],
                         [1, 0, 1],
                         [1, 1, 0]],
                        ["a", "b", "c", "a"],(2, 2, 2))
tf.sparse.to_dense(hypothesis),tf.sparse.to_dense(truth),tf.edit_distance(hypothesis, truth, normalize=True)

(<tf.Tensor: shape=(2, 1, 1), dtype=string, numpy=
 array([[[b'a']],
 
        [[b'b']]], dtype=object)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
 array([[[b'', b''],
         [b'a', b'']],
 
        [[b'b', b'c'],
         [b'a', b'']]], dtype=object)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[inf, 1. ],
        [0.5, 1. ]], dtype=float32)>)

### where
1. 判断条件，满足则返回x，否则返回y；

### reverse_sequence
1. 对input，反转设定长度序列
2. seq_axis，batch_axis；

In [ ]:
seq_lengths = [7, 2, 3, 5]
input_ = [[1, 2, 3, 4, 5, 0, 0, 0], [1, 2, 0, 0, 0, 0, 0, 0],
          [1, 2, 3, 4, 0, 0, 0, 0], [1, 2, 3, 4, 5, 6, 7, 8]]
output = tf.reverse_sequence(input_, seq_lengths, seq_axis=1, batch_axis=0)
output

<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[0, 0, 5, 4, 3, 2, 1, 0],
       [2, 1, 0, 0, 0, 0, 0, 0],
       [3, 2, 1, 4, 0, 0, 0, 0],
       [5, 4, 3, 2, 1, 6, 7, 8]], dtype=int32)>

### quantize
1. 计算分位数


In [ ]:
array_ops.quantize(input_, min_range=0, max_range=10, T="qint32")

Instructions for updating:
`tf.quantize_v2` is deprecated, please use `tf.quantization.quantize` instead.


QuantizeV2(output=<tf.Tensor: shape=(4, 8), dtype=qint32, numpy=
array([[-1717986944, -1288490240,  -858993408,  -429496704,           0,
        -2147483648, -2147483648, -2147483648],
       [-1717986944, -1288490240, -2147483648, -2147483648, -2147483648,
        -2147483648, -2147483648, -2147483648],
       [-1717986944, -1288490240,  -858993408,  -429496704, -2147483648,
        -2147483648, -2147483648, -2147483648],
       [-1717986944, -1288490240,  -858993408,  -429496704,           0,
          429496832,   858993408,  1288490240]], dtype=int32)>, output_min=<tf.Tensor: shape=(), dtype=float32, numpy=0.0>, output_max=<tf.Tensor: shape=(), dtype=float32, numpy=10.0>)

### searchsorted
1. sorted_seq：有序序列
2. values：
3. side：起始查找

In [ ]:
sorted_sequence = [[0, 3, 9, 9, 10],
                   [1, 2, 3, 4, 5]]
values = [[2, 4, 9],
          [0, 2, 6]]
a = array_ops.searchsorted(sorted_sequence, values, side="left")
b = array_ops.searchsorted(sorted_sequence, values, side="right")
a,b

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 2],
        [0, 1, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 4],
        [0, 2, 5]], dtype=int32)>)

### fingerprint
1. 生成输入的指纹值
2. method

In [ ]:
# Calculating result 
a = [0,1,2,3,4,5]
array_ops.fingerprint(a, method = 'farmhash64')

<tf.Tensor: shape=(6, 8), dtype=uint8, numpy=
array([[191, 100,  99, 247, 252,  22, 120, 249],
       [ 84,  24,  96,  84, 195,  82, 124, 105],
       [ 15, 219, 106, 105,  88, 163,  17,  93],
       [ 92,   8,   0, 238, 168, 146,  54,  37],
       [178, 113,  27,   7, 149, 125, 165, 247],
       [172, 241, 253,  71,  91, 205, 163, 224]], dtype=uint8)>