<a href="https://colab.research.google.com/github/Muzhi1920/awesome-models/blob/main/02-basic_tensor_op/02_math_op.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.python.ops import array_ops,math_ops,nn_ops
from tensorflow.python.framework import ops

# 计算

### linspace
1. values increase by `stop - start / num - 1`；
2. [start,stop]的维度，按照axis变换

In [ ]:
tf.linspace([0., 5.], [10., 40.], 5, axis=0),tf.linspace([0., 5.], [10., 40.], 5, axis=-1)

(<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[ 0.  ,  5.  ],
        [ 2.5 , 13.75],
        [ 5.  , 22.5 ],
        [ 7.5 , 31.25],
        [10.  , 40.  ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[ 0.  ,  2.5 ,  5.  ,  7.5 , 10.  ],
        [ 5.  , 13.75, 22.5 , 31.25, 40.  ]], dtype=float32)>)

# 选择

### argmax
1. 返回Tensor中值最大的下标
2. axis，沿轴

In [ ]:
A = tf.constant([2, 20, 30, 3, 6])
tf.math.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
tf.math.argmax(B, 0),tf.math.argmax(B, 1)

(<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2])>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1])>)

In [ ]:
C = tf.constant([0, 0, 0, 0])
tf.math.argmax(C) # Returns smallest index in case of ties

<tf.Tensor: shape=(), dtype=int64, numpy=0>

# 生成

# 转换

# 逻辑