In [1]:
import tensorflow as tf
from tensorflow import feature_column as fc
from tensorflow.keras import initializers, regularizers, constraints, activations
from tensorflow.keras.layers import Layer, InputSpec, Dense, DenseFeatures

## 0.准备工作

In [2]:
nums = fc.numeric_column('nums', dtype=tf.float32)
seq = fc.categorical_column_with_hash_bucket('seq', hash_bucket_size=10, dtype=tf.int64)
target = fc.categorical_column_with_hash_bucket('target', hash_bucket_size=10, dtype=tf.int64)
seq_col = fc.embedding_column(seq, dimension=8)
target_col = fc.embedding_column(target, dimension=8)
columns = [seq_col, target_col, nums]
features={
    "seq": tf.sparse.SparseTensor(
        indices=[[0, 0], [0, 1], [1, 0], [1, 1], [2, 0]],
        values=[1100, 1101, 1102, 1101, 1103],
        dense_shape=[3, 2]),
    "target": tf.sparse.SparseTensor(
        indices=[[0, 0],[1,0],[2,0]],
        values=[1102,1103,1100],
        dense_shape=[3, 1]),
    "nums": tf.convert_to_tensor([0.1,0.2,0.3]) 

}
tf.sparse.to_dense(features['seq'])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1100, 1101],
       [1102, 1101],
       [1103,    0]], dtype=int32)>

In [3]:
input_layer = DenseFeatures(columns, name='features_input_layer')
net = input_layer(features)
net

<tf.Tensor: shape=(3, 17), dtype=float32, numpy=
array([[ 0.1       ,  0.07652323,  0.0585428 ,  0.08151767, -0.2022036 ,
         0.06565414, -0.3711438 , -0.02516507,  0.21639498,  0.0969201 ,
         0.2617676 ,  0.30773577,  0.27656987, -0.58664036, -0.07684607,
        -0.3052424 ,  0.37237114],
       [ 0.2       , -0.05664414, -0.08806539,  0.41720438, -0.385957  ,
        -0.20728785, -0.6272269 , -0.15692909,  0.03670049, -0.02287794,
         0.41714737,  0.15411732, -0.18766867,  0.45284638,  0.08314946,
        -0.2844527 ,  0.21679816],
       [ 0.3       , -0.26379678,  0.21619137,  0.47894743, -0.06796242,
         0.00776523,  0.44499773,  0.29921588,  0.22894183, -0.5644205 ,
        -0.14550486, -0.12944674, -0.4994151 , -0.02337713, -0.24291673,
         0.03023304,  0.1539555 ]], dtype=float32)>